[project]
name = "f1-dash"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "fastf1>=3.5.3",
    "ipykernel>=6.29.5",
    "meteostat>=1.6.8",
    "pandas>=2.2.3",
    "tqdm>=4.67.1",
]

[dependency-groups]
dev = [
    "apache-airflow>=3.0.1",
]
